apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  type: LoadBalancer    
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    service: reverseproxy