version: "3"
networks:
  udagram:
    driver: bridge
services:
  reverseproxy:
    image: datacamp265/reverseproxy
    build:
      context: .
    ports:
      - 8080:8080
    restart: always
    networks:
      - udagram
  backend-user:
    image: datacamp265/udacity-restapi-user
    build:
      context: ../../udacity-restapi-user/
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    networks:
      - udagram
  backend-feed:
    image: datacamp265/udacity-restapi-feed
    build:
      context: ../../udacity-restapi-feed/
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: $URL
    networks:
      - udagram
  frontend:
    image: datacamp265/udacity-frontend
    build:
      context: ../../udacity-frontend/
    ports:
      - "8100:80"
    networks:
      - udagram